// 17 System Roles defined in 00_MASTER.md
const ROLES = {
  PATIENT: 'PATIENT',
  RECEPTIONIST: 'RECEPTIONIST',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  RADIOLOGY_TECHNICIAN: 'RADIOLOGY_TECHNICIAN',
  HOUSEKEEPING: 'HOUSEKEEPING',
  MAINTENANCE: 'MAINTENANCE',
  ADMIN_MANAGER: 'ADMIN_MANAGER',
  HR_MANAGER: 'HR_MANAGER',
  BILLING_STAFF: 'BILLING_STAFF',
  INSURANCE_REPRESENTATIVE: 'INSURANCE_REPRESENTATIVE',
  PROCUREMENT_OFFICER: 'PROCUREMENT_OFFICER',
  VENDOR: 'VENDOR',
  HOSPITAL_MANAGEMENT: 'HOSPITAL_MANAGEMENT',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN'
};

// Portal to Role Mapping (5 Portals defined in 00_MASTER.md)
const PORTAL_ROLES = {
  PATIENT_PORTAL: [ROLES.PATIENT],
  CLINICAL_PORTAL: [ROLES.DOCTOR, ROLES.NURSE],
  OPERATIONS_PORTAL: [
    ROLES.RECEPTIONIST,
    ROLES.PHARMACIST,
    ROLES.LAB_TECHNICIAN,
    ROLES.RADIOLOGY_TECHNICIAN,
    ROLES.HOUSEKEEPING,
    ROLES.MAINTENANCE
  ],
  FINANCE_PORTAL: [ROLES.BILLING_STAFF, ROLES.INSURANCE_REPRESENTATIVE],
  ADMIN_PORTAL: [
    ROLES.ADMIN_MANAGER,
    ROLES.HR_MANAGER,
    ROLES.PROCUREMENT_OFFICER,
    ROLES.HOSPITAL_MANAGEMENT,
    ROLES.SYSTEM_ADMIN
  ]
};

module.exports = {
  ROLES,
  PORTAL_ROLES,
  ALL_ROLES: Object.values(ROLES)
};
